platform :android do
    desc 'Build the Android application.'
    lane :build do
      gradle(task: 'clean', project_dir: 'android/')
      gradle(task: 'assemble', build_type: 'debug', project_dir: 'android/')
    end
  end